### ISSUE TITLE
Replace usage of contains and contained in

### ISSUE THREAD

**Issue by cmungall** [insect-morphology/aism#75]
See https://github.com/oborel/obo-relations/pull/739

Note I think the existing usages are wrong

http://purl.obolibrary.org/obo/AISM_0000007

[contains](https://ontobee.org/ontology/AISM?iri=http://purl.obolibrary.org/obo/RO_0001019) some [pro-resilin (fruit fly)](https://ontobee.org/ontology/AISM?iri=http://purl.obolibrary.org/obo/PR_Q9V7U0)

You are saying there that elastic cuticle is only found in Drosophila melanogaster

**Comment by JCGiron** [comment]
We updated '[elastic cuticle](http://purl.obolibrary.org/obo/AISM_0000007)' to be defined as a SubClass Of '[composed primarily of](http://purl.obolibrary.org/obo/RO_0002473)' some [resilin](http://purl.obolibrary.org/obo/AISM_0000001).
We created [resilin](http://purl.obolibrary.org/obo/AISM_0000001) with a broader definition: "an elastomeric protein found in many insects and other arthropods. It provides soft rubber-elasticity to mechanically active organs and tissue", since the only previously existing instance of resilin was [pro-resilin (fruit fly)](http://purl.obolibrary.org/obo/PR_Q9V7U0), which is defined as "A protein that is a translation product of the resilin gene in fruit fly."
This change was incorporated in version [v2024-02-21](https://github.com/insect-morphology/aism/tree/v2024-02-21)
